defaults: &defaults
  working_directory: ~/repo

node_cache_key: &node_cache_key v1-dependencies-{{ checksum "yarn.lock" }}

defaults_js: &defaults_js
  <<: *defaults
  docker:
    - image: circleci/node:10.14.1

restore_node_cache: &restore_node_cache
  restore_cache:
    keys:
      - *node_cache_key

save_node_cache: &save_node_cache
  save_cache:
    paths:
      - node_modules
    key: *node_cache_key

install_node_modules: &install_node_modules
  run: yarn install --frozen-lockfile --no-progress --non-interactive --network-concurrency 1

version: 2
jobs:
  compile:
    <<: *defaults_js
    steps:
      - checkout
      - *restore_node_cache
      - *install_node_modules
      - *save_node_cache
      # TODO: add additional steps here
      - run: yarn build

  tests:
    <<: *defaults_js
    steps:
      # Install azure-functions-core-tools
      # see https://github.com/Azure/azure-functions-core-tools#debian-9
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install apt-transport-https
            wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
            sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
            wget -q https://packages.microsoft.com/config/debian/9/prod.list
            sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
            sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
            sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
            sudo apt-get update
            sudo apt-get install azure-functions-core-tools

      - checkout
      - *restore_node_cache
      - *install_node_modules

      - run: yarn test
      - run: "bash <(curl -s https://codecov.io/bash)"

  lint:
    <<: *defaults_js
    steps:
      - checkout
      - *restore_node_cache
      - *install_node_modules
      - run: yarn lint

  danger:
    <<: *defaults_js
    steps:
      - checkout
      - *restore_node_cache
      - *install_node_modules
      - run: '[ -z "$DANGER_GITHUB_API_TOKEN" ] || yarn danger ci'

workflows:
  version: 2
  build:
    jobs:
      - compile
      - tests
      - lint
      - danger:
          filters:
            branches:
              ignore: master
